### ISSUE TITLE
calculate处理方式可以优化，以单个最简单的SUM(1,2,3,4,5,6,7,8,9,10)为例

### ISSUE THREAD

**Issue by lijie1024512** [Xy-Zipper/vue-formula-editor#6]
![image](https://github.com/user-attachments/assets/c6be5f1c-1e36-4c95-8017-eca58c321968)
![image](https://github.com/user-attachments/assets/42ffbed9-fc9d-4a38-8041-30ef736e662a)
formulajs方法有422个函数，这种遍历key和value的方式有点耗时，直接处理会简单很多，如果需要result的str作为关系载体的话，我给出的方案是直接把formula.js挂window，或者初始化的时候存起来，然后result的字符串形式就变成formulajs.SUM(1,2,3,4,5,6,7,8,9,10),可以提高不少性能

**Comment by Xy-Zipper** [comment]
新版优化了性能： [v0.2.0](https://github.com/Xy-Zipper/vue-formula-editor/tree/v0.2.0) @lijie1024512
